# Generated by Django 5.1.1 on 2024-09-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_apis', '0004_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='canceled_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
