# Generated by Django 5.1.1 on 2024-09-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_apis', '0005_appointment_canceled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='scheduled', max_length=10),
        ),
    ]
